### ISSUE TITLE
Delly VCF missing reference allele with picard RenameSampleInVcf

### ISSUE THREAD

**Issue by cagaser** [dellytools/delly#170]
Hello community, 

I am having an issue with renaming a sample in Delly VCF file.

```
picard RenameSampleInVcf INPUT=delly.vcf OUTPUT=.delly.renamed.test.vcf" NEW_SAMPLE_NAME="Test"
```
I get the following error:

```
Exception in thread "main" htsjdk.tribble.TribbleException: The provided VCF file is malformed at approximately line number 56793: The reference allele cannot be missing, for input source: file:///exports/xx/analysis/16_germline_dna_biowdl/samples/smpl_xxx/delly/delly.vcf
        at htsjdk.variant.vcf.AbstractVCFCodec.generateException(AbstractVCFCodec.java:801)
        at htsjdk.variant.vcf.AbstractVCFCodec.checkAllele(AbstractVCFCodec.java:596)
        at htsjdk.variant.vcf.AbstractVCFCodec.parseAlleles(AbstractVCFCodec.java:555)
        at htsjdk.variant.vcf.AbstractVCFCodec.parseVCFLine(AbstractVCFCodec.java:358)
        at htsjdk.variant.vcf.AbstractVCFCodec.decodeLine(AbstractVCFCodec.java:299)
        at htsjdk.variant.vcf.AbstractVCFCodec.decode(AbstractVCFCodec.java:277)
        at htsjdk.variant.vcf.AbstractVCFCodec.decode(AbstractVCFCodec.java:64)
        at htsjdk.tribble.AsciiFeatureCodec.decode(AsciiFeatureCodec.java:70)
        at htsjdk.tribble.AsciiFeatureCodec.decode(AsciiFeatureCodec.java:37)
        at htsjdk.tribble.TribbleIndexedFeatureReader$WFIterator.readNextRecord(TribbleIndexedFeatureReader.java:373)
        at htsjdk.tribble.TribbleIndexedFeatureReader$WFIterator.next(TribbleIndexedFeatureReader.java:354)
        at htsjdk.tribble.TribbleIndexedFeatureReader$WFIterator.next(TribbleIndexedFeatureReader.java:315)
        at picard.vcf.RenameSampleInVcf.doWork(RenameSampleInVcf.java:138)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:295)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)
```
Here is the line in the VCF
```
#CHROM  POS     ID      REF     ALT     QUAL    FILTER 
chrUn_KI270435v1        93013   BND00056554     .       .,.,[chr15:17081612[    .       PASS

```

**Comment by tobiasrausch** [comment]
I am not sure, I am not using picard. Maybe just drop the unplaced chromosomes first chrUn_* ?

**Comment by tobiasrausch** [comment]
Has this issue been solved?  If not please re-open.
