### ISSUE TITLE
"delly  merge" core dumped when unrecognised option 

### ISSUE THREAD

**Issue by wangyugui** [dellytools/delly#62]
Hi.

"delly  merge" core dumped when unrecognised option.
Although this is not a normal case.

```
# delly  merge --version
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::program_options::unknown_option> >'
  what():  unrecognised option '--version'
Aborted (core dumped)

(gdb) where
#0  0x00000000005f528b in raise ()
#1  0x00000000005fee38 in abort ()
#2  0x000000000057af15 in __gnu_cxx::__verbose_terminate_handler() ()
#3  0x00000000005798a6 in __cxxabiv1::__terminate(void (*)()) ()
#4  0x00000000005798d3 in std::terminate() ()
#5  0x0000000000578be9 in __cxa_rethrow ()
#6  0x00000000004eeb3b in boost::program_options::detail::cmdline::finish_option(boost::program_options::basic_option<char>&, std::vector<std::string, std::allocator<std::string> >&, std::vector<boost::function1<std::vector<boost::program_options::basic_option<char>, std::allocator<boost::program_options::basic_option<char> > >, std::vector<std::string, std::allocator<std::string> >&>, std::allocator<boost::function1<std::vector<boost::program_options::basic_option<char>, std::allocator<boost::program_options::basic_option<char> > >, std::vector<std::string, std::allocator<std::string> >&> > > const&) ()
#7  0x00000000004ef131 in boost::program_options::detail::cmdline::run() ()
#8  0x000000000044be8b in boost::program_options::basic_command_line_parser<char>::run() ()
#9  0x0000000000407b2b in torali::merge(int, char**) ()
#10 0x0000000000402420 in main ()
(gdb)
#
```

**Comment by tobiasrausch** [comment]
As written in the error message, '--version' does not exist for the delly subcommands.

./delly shows the version in the header and ./delly --version also works.
