### ISSUE TITLE
delly call --type BND failed to report var to VCF when one split-read pair

### ISSUE THREAD

**Issue by wangyugui** [dellytools/delly#90]
Hi.

delly call --type BND failed to report var to VCF when one split-read pair.

version:v0.7.7

```
# delly-v0.7.7 call -g ${dnaref}  --type BND -o delly.bcf delly.sort.bam
[2018-Jan-10 23:10:43] delly call -g /usr/bio-ref/GRCh38.p11.dnaref/dnaref.fa --type BND -o delly.bcf delly.sort.bam
[2018-Jan-10 23:10:43] Paired-end clustering

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
[2018-Jan-10 23:10:43] Library statistics
Sample: test_delly
RG: ID=test_delly,ReadSize=300,AvgDist=23180364,EstCov=1.2942e-05,MappedAsPair=0,Median=0,MAD=0,Layout=0,MaxSize=0,MinSize=0,UniqueDiscordantPairs=0
[2018-Jan-10 23:10:43] Done.
#
```

It reported 'MappedAsPair=0'; but 'samtools view ' show that there are one pair.

```
# samtools view delly.sort.bam
DELLY_SPLIT     129     9       130713881       60      200M    22      23180365        0       GGTTGGTGACTTCCACAGGAAAAGTTCTGGAGGAGTAGCCAAAGACCATCAGCGTTTCCTTTATGTGTGAGAATTGAAATGACTAGCATTATTGACCCTTTTCAGCATCCCCTGTGAATATTTCTGTTTAGGTTTTTCTTCTTGAAAAGAAATTGTTATTCAGCCCGTTTAAAACAAATCAAGAAACTTTTGGGTAACAT        <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<    NM:i:0  MD:Z:200        MC:Z:200M100S   AS:i:200    XS:i:0  RG:Z:test_delly
DELLY_SPLIT     2129    9       130713981       60      100M200H        =       130713881       -200    TTCAGCATCCCCTGTGAATATTTCTGTTTAGGTTTTTCTTCTTGAAAAGAAATTGTTATTCAGCCCGTTTAAAACAAATCAAGAAACTTTTGGGTAACAT        <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<        NM:i:0  MD:Z:100        MC:Z:200M       AS:i:100        XS:i:21 RG:Z:test_delly SA:Z:22,23180365,+,200M100S,60,0;
DELLY_SPLIT     65      22      23180365        60      200M100S        9       130713881       0       GGGGGGAGGGTGGCGGCTCGATGGGGGAGCCGCCTCCAGGGGGCCCCCCCGCCCTGTGCCCACGGCGCGGCCCCTTTAAGAGGCCCGCCTGGCTCCGTCATCCGCGCCGCGGCCACCTCCCCCCGGCCCTCCCCTTCCTGCGGCGCAGAGTGCGGGCCGGGCGGGAGTGCGGCGAGAGCCGGCTGGCTGAGCTTAGCGTCATGTTACCCAAAAGTTTCTTGATTTGTTTTAAACGGGCTGAATAACAATTTCTTTTCAAGAAGAAAAACCTAAACAGAAATATTCACAGGGGATGCTGAA    <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<        NM:i:0  MD:Z:200        MC:Z:200M       AS:i:200        XS:i:0  RG:Z:test_delly SA:Z:9,130713981,-,100M200S,60,0;
#
```

which rule is it filtered  by?

**Comment by wangyugui** [comment]
[delly.sort.bam.zip](https://github.com/dellytools/delly/files/1619366/delly.sort.bam.zip)

This is the bam file to test delly.

**Comment by tobiasrausch** [comment]
Delly needs to estimate the insert size of every read-group in your BAM file for paired-end genotyping and deletion discovery. Delly only accepts read-groups with >10,000 valid pairs. If you want to simulate SVs please make sure you have enough "normal" paired-ends in your BAM file so Delly can estimate the insert size accurately. Whenever the log output states RG: ...,Median=0 the read-group did not have enough pairs and Delly treats this RG as a single-end library and thus, it is ignored for SV calling.

**Comment by wangyugui** [comment]
I add 12000 pair to this bam. 

and then there is still nothing reported by delly-0.7.7.

```
+ delly-v0.7.7 call --type BND -g /usr/bio-ref/GRCh38.p11.dnaref/dnaref.fa -o delly.bcf delly.sort.bam
[2018-Jan-10 23:37:35] delly call --type BND -g /usr/bio-ref/GRCh38.p11.dnaref/dnaref.fa -o delly.bcf delly.sort.bam
[2018-Jan-10 23:37:35] Paired-end clustering

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
[2018-Jan-10 23:37:35] Library statistics
Sample: test_delly
RG: ID=test_delly,ReadSize=200,AvgDist=0,EstCov=inf,MappedAsPair=0.999917,Median=200,MAD=0,Layout=3,MaxSize=200,MinSize=200,UniqueDiscordantPairs=1
[2018-Jan-10 23:37:35] Done.
```
and an exception of delly-git-source.
```
delly call --type BND -g /usr/bio-ref/GRCh38.p11.dnaref/dnaref.fa -o delly-git.bcf delly.sort.bam
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::program_options::unknown_option> >'
  what():  unrecognised option '--type'
./test.delly.sh: line 74: 59299 Aborted                 (core dumped) delly call --type BND -g ${dnaref} -o delly-git.bcf delly.sort.bam


(gdb) where
#0  0x00000000005bf49b in raise ()
#1  0x00000000005c9418 in abort ()
#2  0x0000000000585fc5 in __gnu_cxx::__verbose_terminate_handler() ()
#3  0x0000000000535536 in __cxxabiv1::__terminate(void (*)()) ()
#4  0x0000000000535563 in std::terminate() ()
#5  0x00000000005356c9 in __cxa_rethrow ()
#6  0x000000000048698b in boost::program_options::detail::cmdline::finish_option(boost::program_options::basic_option<char>&, std::vector<std::string, std::allocator<std::string> >&, std::vector<boost::function1<std::vector<boost::program_options::basic_option<char>, std::allocator<boost::program_options::basic_option<char> > >, std::vector<std::string, std::allocator<std::string> >&>, std::allocator<boost::function1<std::vector<boost::program_options::basic_option<char>, std::allocator<boost::program_options::basic_option<char> > >, std::vector<std::string, std::allocator<std::string> >&> > > const&) ()
#7  0x0000000000486f81 in boost::program_options::detail::cmdline::run() ()
#8  0x00000000004402fb in boost::program_options::basic_command_line_parser<char>::run() ()
#9  0x00000000004138d0 in torali::delly(int, char**) ()
#10 0x000000000040299a in main ()

#

```

**Comment by wangyugui** [comment]
@tobiasrausch 

I added 12000 reads to this bam.

both delly-0.7.7 and delly-git-source reported nothing.


```
+ delly-v0.7.7 call --type BND -g /usr/bio-ref/GRCh38.p11.dnaref/dnaref.fa -o delly.bcf delly.sort.bam
[2018-Jan-10 23:46:19] delly call --type BND -g /usr/bio-ref/GRCh38.p11.dnaref/dnaref.fa -o delly.bcf delly.sort.bam
[2018-Jan-10 23:46:19] Paired-end clustering

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
[2018-Jan-10 23:46:19] Library statistics
Sample: test_delly
RG: ID=test_delly,ReadSize=200,AvgDist=0,EstCov=inf,MappedAsPair=0.999917,Median=300,MAD=0,Layout=2,MaxSize=300,MinSize=300,UniqueDiscordantPairs=1
[2018-Jan-10 23:46:19] Done.
+ delly call -g /usr/bio-ref/GRCh38.p11.dnaref/dnaref.fa -o delly-git.bcf delly.sort.bam
[2018-Jan-10 23:46:19] delly call -g /usr/bio-ref/GRCh38.p11.dnaref/dnaref.fa -o delly-git.bcf delly.sort.bam
[2018-Jan-10 23:46:19] Paired-end clustering

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
[2018-Jan-10 23:46:23] Library statistics
Sample: test_delly
RG: ID=test_delly,ReadSize=200,Median=300,MAD=0,UniqueDiscordantPairs=12001
[2018-Jan-10 23:46:23] Done.
```

[delly.sort.bam.zip](https://github.com/dellytools/delly/files/1619471/delly.sort.bam.zip)

This is the bam for test.

**Comment by tobiasrausch** [comment]
delly call -t BND fails for the latest github code because I am in the
process of merging all SV types. For the latest release v0.7.7 the option
-t BND should work.

Sorry, I didn't read your first message entirely but Delly only calls an SV
if >=2 pairs support it.

**Comment by wangyugui** [comment]
With 2 pairs support it, delly(git-source) works well now. delly-0.7.7 failed, but we have a working version now.

Thanks a lot.
